apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flix-cluster
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    maxSize: 3
    minSize: 1
